version: '3'
services:
  wp:
    image: ${SITE_IMAGE:-wordpress}:${SITE_VERSION:-latest}
    container_name: wp
    restart: always
    volumes:
      - ./app/wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wpdb
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - 80:80
      - 443:443
  db:
    image: ${DB_IMAGE:-mariadb}:${DB_VERSION:-latest}
    container_name: db
    restart: always
    command: "--default-authentication-plugin=mysql_native_password"
    volumes:
      - ./app/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: wpdb
      MYSQL_USER: user
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORT: ${MYSQL_PASSWORD}
